services:
  backend:
    build:
      context: .
      dockerfile: docker/local/demo-backend/Dockerfile

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8443:443"
